/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edu_edumediaplayer_playback_MP3Reader */

#ifndef _Included_com_edu_edumediaplayer_playback_MP3Reader
#define _Included_com_edu_edumediaplayer_playback_MP3Reader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_edu_edumediaplayer_playback_MP3Reader
 * Method:    readHeader
 * Signature: (Ljava/lang/String;)Lcom/edu/edumediaplayer/playback/SongFileInfo;
 */
JNIEXPORT jobject JNICALL Java_com_edu_edumediaplayer_playback_MP3Reader_readHeader
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_edu_edumediaplayer_playback_MP3Reader
 * Method:    readPcm
 * Signature: (Ljava/lang/String;)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_edu_edumediaplayer_playback_MP3Reader_readPcm
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
